coverage:
    status:
      project:
        default: on
        flag_1:
            flags:
                - flag_1
      patch:
        flag_1:
            flags:
                - flag_1
      changes:
        true

flags:
    flag_1:
        carryforward: false
    flag_2:
        carryforward: false